language: cpp
sudo: required
dist: xenial
compiler:
- gcc
os:
- linux

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y zlib1g zlib1g-dev libminizip-dev minizip libminizip1 gcc-7 g++-7
  - cmake --version
  - mkdir build
  - cd build
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake ..

script: make

after_success:
  - wget https://raw.githubusercontent.com/not0xFF/PurpleHLE/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discordapp.com/api/webhooks/453288315685437440/-y-mE0WiHlDP_T9VZXgayh7qGECUlXC4q2s_wfiCyXENyGwI3_BqUSjBPdUbMYrNgm-6
after_failure:
  - wget https://raw.githubusercontent.com/not0xFF/PurpleHLE/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/453288315685437440/-y-mE0WiHlDP_T9VZXgayh7qGECUlXC4q2s_wfiCyXENyGwI3_BqUSjBPdUbMYrNgm-6
